name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  schedule:
    - cron: '33 3 * * 0'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          no-cache: true
          pull: true
          push: true
          tags: |
            netsandbox/request-tracker-base:latest
            ghcr.io/${{ github.repository_owner }}/request-tracker-base:latest
